swagger: '2.0'
info:
  title: HTTP API Console forest.forest
  name: ''
  description: ''
paths:
  /forest/forest/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
  /forest/forest/say/{name}:
    get:
      operationId: Query_Say
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              name:
                type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Query
  /forest/forest/say_hello/{name}:
    get:
      operationId: Query_SayHello
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              name:
                type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: name
          in: path
          required: true
          type: string
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  Params:
    type: object
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  QuerySayHelloResponse:
    type: object
    properties:
      name:
        type: string
  QuerySayResponse:
    type: object
    properties:
      name:
        type: string
  MsgUpdateParamsResponse:
    type: object
